version: "3"
services:
  node:
    image: test/node-app:0.1
    container_name: taglessNode
    ports: 
      - "33000:3000"
    volumes:
      - ~/node/tagless/webapps:/usr/src/app
      - ~/node/tagless/logs:/usr/src/logs
      - ~/node/tagless/temp:/usr/src/temp
    tty: true
    stdin_open: true 
